name: SimpleCoinsAPI
author: GermanElectronix
version: 1.1

main: de.germanelectronix.simplecoins.SimpleCoins

commands:
  coins:
    description: Get a players coins
    usage: /coins [player]
  setcoins:
    description: Set a players coins
    usage: /setcoins [value] OR /setcoins [player] [value]
  addcoins:
    description: Add coins to a players wallet
    usage: /addcoins [amount] OR /addcoins [player] [amount]
  takecoins:
    description: Substract coins from a players wallet
    usage: /takecoins [amount] OR /takecoins [player] [amount]

permissions:
  simplecoins:
    simplecoins.getcoins: true
    simplecoins.getcoins.others: true
    simplecoins.setcoins: true
    simplecoins.setcoins.others: true
    simplecoins.addcoins: true
    simplecoins.addcoins.others: true
    